version: '3.7'

services:

 prom:
  image: prom/prometheus:latest
  volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  command: '--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus'
  ports:
  - 9090:9090
  external_links:
  - matching-engine 
  networks:
   - monitoring
   - back
  
 grafana:
   image: grafana/grafana
   ports:
    - 3000:3000
   depends_on:
    - prom
   networks:
    - monitoring

networks:
 monitoring:
  driver: bridge
  external: true
 back: 
  external: true